### ISSUE TITLE
又来打扰了：连接数据库后无法create文章

### ISSUE THREAD

**Issue by edwardstudy** [sskyy/twenty#3]
## 如题，点击submit后。服务器端报错：

error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
: key category.id must not contain '.'
    at Error (<anonymous>)
    at Function.checkKey (/usr/node/twenty-fullpackage/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:1450:13)
    at serializeObject (/usr/node/twenty-fullpackage/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:356:14)
    at packElement (/usr/node/twenty-fullpackage/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:858:23)
    at serializeObject (/usr/node/twenty-fullpackage/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:343:15)
    at packElement (/usr/node/twenty-fullpackage/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:858:23)
    at serializeObject (/usr/node/twenty-fullpackage/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:360:15)
    at Function.serializeWithBufferAndIndex (/usr/node/twenty-fullpackage/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:332:10)
    at BSON.serializeWithBufferAndIndex (/usr/node/twenty-fullpackage/node_modules/sails-mongo/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:1532:15)
    at QueryCommand.toBinary (/usr/node/twenty-fullpackage/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/commands/query_command.js:232:35)
## 页面没有反应。console报错：

POST http://222.31.76.67:1337/post 500 (Internal Server Error) angular.min.js:78
## Object {error: "E_UNKNOWN", status: 500, summary: "Encountered an unexpected error", raw: Object}

但是category下能新建分类，数据库中‘分类’集也正常。
数据库用的是mongodb。

**Comment by edwardstudy** [comment]
当然如果不添加分类，就能成功创建文章。

**Comment by sskyy** [comment]
@EdwardStudy  不好意思，刚放假回来。好像你装的是那个打包好的版本。那个版本确实有问题，后来马上修复了。还是从git上clone来装吧，这样可以保证是最新的，而且目前已知的bug都已经修复了。

**Comment by edwardstudy** [comment]
谢谢，我clone下来了，不过还是存在这个问题。我翻阅zorejs的github，是不是文章的 category、tag还没有完成呢？
